Force example specification
spajic/lobanov pull request #10
Opened 2022-03-29 15:37 UTC by bagdenia

2022-04-01 13:11 UTC, spajic requested changes
see a comment pls

2022-04-01 13:11 UTC, spajic commented on lib/lobanov/schema_by_object.rb
> +          raise MissingExampleError.new("for #{key.inspect} in #{obj}")
Это не совсем удобный подход оказался на практике.

Lobanov может сгенерить спеку по ответу, в котором некоторые поля nil.

_Спека должна генерироваться без ошибок_, но там будет поле, про которое известно только его имя и то, что оно nullable: true.

Дальше, при повторном прогоне теста, когда выполняется уже валидация сохранённой схемы, я предлагаю выкидываеть ошибку в случае если у поля нет type и example.

Так
- lobanov генерит скелетон по твоему спеку
- далее подсказывает тебе где у тебя поле с непонятным типом
- заставляет тебя разобраться какой там должен быть тип и прописать его в схему руками
- после этого тест начинает проходить, всё хорошо
- nullable: true при этом убирать не надо

И я предлагаю ошибку выкидывать похоже на это https://github.com/spajic/lobanov/blob/main/lib/lobanov/validator.rb#L53

То есть не сам объект, где не хватает примера, а путь->к->полю->внутри->объекта

2022-04-07 12:39 UTC, bagdenia commented on lib/lobanov/schema_by_object.rb
> +          raise MissingExampleError.new("for #{key.inspect} in #{obj}")
up

2022-04-07 15:27 UTC, spajic commented on lib/lobanov.rb
> +      ValidateNullable.call(stored_schema: stored_response_schema )
лишний пробел перед скобочкой :trollface:

2022-04-07 15:33 UTC, spajic commented on lib/lobanov/validate_nullable.rb
> +  class ValidateNullable
Тут немного другой акцент смысловой

`ValidateFieldsHaveExamplesAndTypes' примерно

мы проверяем, что должны быть типы и примеры

Просто если поле `nullable`, то в тесте мы разрешаем не возвращать значение.

Но мы не разрешаем вообще не иметь примера и типа в схеме.

То есть проверки на nullable тут не нужны на самом деле

Тут что-то вроде

```ruby
  if value['type'].nil? # добавить ошибку MissingTypeError
  if value['example'].nil? # добавить ошибку MissingExampleError
```

2022-04-07 15:33 UTC, spajic reviewed
See comment

2022-04-08 10:40 UTC, spajic approved these changes
👍👍 то что надо

2022-04-08 10:40 UTC, merged